### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#10]
I'd say the highest priorities are adding tests for the various tools (so that we get a warning if their output format changes) and for the various file- and configuration-overlaying parts (making sure user directories correctly override default settings, testing profile inheritance, etc.). If that sounds good to you, I'll take a crack at it next month once I have the hours.

**Comment by denewiler** [comment]
That sounds great! If you get started let me know, since that is something I was thinking about attempting as well. I don't know if I'll have time in the near term either. Thanks.

**Comment by creffett** [comment]
@tdenewiler no preference really, do you have one you'd like to use? I will probably work on this issue this month (as usual, with the caveat that we're waiting on release approval before I can push you my changes)

**Comment by tdenewiler** [comment]
I have not written unit tests in Python before. I did a little bit of research and I would start with nose, based on that it looks easier to write and maintain tests, and there are some larger ROS packages that base their Python unit tests on nose. If anyone had better reasons or experience with the tools I would easily be convinced to start with a different tool.
