### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#12]
I was able to release into Test Pypi repository but Statick had trouble running in a virtualenv. Some care must be taken to figure out how to install dependencies, especially apt-based dependencies.

The goal is that Travis jobs can `pip install statick` and then use some of the included levels for testing. I want to be careful that ROS dependencies are only installed when required. Pure Python or CMake based projects should not need to setup the ROS apt repositories in order to use Statick.

**Comment by denewiler** [comment]
This has been done for a while. See https://pypi.org/project/statick/.
