### ISSUE TITLE
Idea: add support for reporting to be plugin-based

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#13]
Currently, we do reporting by printing to the console. Given that the ROS-M contract we're working will probably involve posting results to a REST endpoint, and that will probably be a very specific format, I'm wondering if it would make sense to have reporting plugins in a similar setup to the scanning and tool use plugins. Then people can just drop in the reporting plugins they want - print to console, write to file, send to REST endpoint, etc. Thoughts?

**Comment by xydesa** [comment]
I like that idea, outputting xml could be another useful plugin.

**Comment by creffett** [comment]
I'm working on this one for some of SoarTech's ROS work, but am currently waiting for some clarification about our releasability policy from the customer before pushing anything.

**Comment by creffett** [comment]
Work's done on my end, just waiting for release approval. Will have a PR as soon as that's ready.

**Comment by creffett** [comment]
Fixed in MR #77
