### ISSUE TITLE
Build on Windows and OSX

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#134]
It would be interesting to run the build and unit tests on more operating systems to include Windows and OSX. Some examples of how to do that are at https://docs.travis-ci.com/user/multi-os/. Those examples include ways to ignore errors on certain operating systems. That way we could start adding support a bit at a time.

**Comment by tdenewiler** [comment]
Trying to build on windows and the following error occurs:

```
The language 'python' is currently unsupported on the Windows Build Environment.
```

We'll skip adding windows support for the time being.

**Comment by denewiler** [comment]
This is being worked on in #215 as part of switching from Travis CI to Github Actions.

**Comment by denewiler** [comment]
Done in #215.
