### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#166]
Statick transitively depends on the `pathspec` package (via yamllint), which dropped support for Python 3.4 in their latest release this week: [0.7.0](https://pypi.org/project/pathspec/). The work was done in cpburnz/python-path-specification#28. This is causing our Travis jobs to fail (see #165) on the Python 3.4 job.

I am going to drop support for testing against Python 3.4. It was end-of-lifed 2019-03-18 (https://www.python.org/downloads/release/python-3410/). If there is a desire by users to keep supporting Python 3.4 we could do something along the lines of trying to have that Travis job use a pinned version of the pathspec package at version 0.6.0. That seems like it might cause more issues requiring more and more package pinning over time.

**Comment by denewiler** [comment]
Done in #167.
