### ISSUE TITLE
Make output files optional

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#171]
Statick currently requires an output directory, where issues found will be written to a file. There are alternative reporting mechanisms, but this one is required. I would like to make the output directory an argument that is not required. If no output directory is specified via arguments, then the write file reporting plugin will not attempt to write results to a file. We will also disable any checks to see if the output directory exists.

This will be a breaking change. If the output directory is desired, then the invocation of Statick will need to change from:

```
statick my-project statick-output
```

to

```
statick my-project --output-directory statick-output
```

However, the following command will be valid and will provide feedback to the user. It will also return success or failure as an exit code the same as now.

```
statick my-project
```

Any issues found will still be printed to screen, and no other reporting plugins will be modified.

**Comment by denewiler** [comment]
Done in #173.
