### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#19]
The Travis CI jobs are failing to build. The step that is failing is `travis-sphinx build`. I have not been able to figure out yet if the error is introduced from a specific change to statick or if it is a change in the upstream packages sphinx or travis-sphinx. The same commit on the master branch built successfully one day, then a few days later it failed when building again in Travis.

In the failing job I see these upstream versions:

    Downloading https://files.pythonhosted.org/packages/2f/2a/c82e6ca945d05a540a70bd464fd043ea6d6b99168d949e2ad009380bf540/Sphinx-1.8.0-py2.py3-none-any.whl
    Downloading https://files.pythonhosted.org/packages/02/20/c2483fef66a69281af8e013e7146c02a4ab9cd7a289615b86b5d7554ef20/travis-sphinx-2.2.1.tar.gz

In the most recent successful job I see these upstream versions:

    Downloading https://files.pythonhosted.org/packages/90/f9/a0babe32c78480994e4f1b93315558f5ed756104054a7029c672a8d77b72/Sphinx-1.7.9-py2.py3-none-any.whl (1.9MB)
    Downloading https://files.pythonhosted.org/packages/02/20/c2483fef66a69281af8e013e7146c02a4ab9cd7a289615b86b5d7554ef20/travis-sphinx-2.2.1.tar.gz

The job is using the same version of travis-sphinx but the version of sphinx bumped from `1.7.9` to `1.8.0`.

The error message is:

```
$ travis-sphinx build
Running Sphinx v1.8.0
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/highlighting.py", line 26, in <module>
    from sphinx.ext import doctest
SyntaxError: unqualified exec is not allowed in function 'run' it contains a nested function with free variables (doctest.py, line 97)
The full traceback has been saved in /tmp/sphinx-err-0LgVhc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error: Error building sphinx doc
The command "travis-sphinx build" exited with 1.
```

**Comment by creffett** [comment]
I'm thinking it might make sense to pin those sphinx versions and put them in a separate requirements.txt.

**Comment by denewiler** [comment]
Pinning worked. Good call @creffett.
