### ISSUE TITLE
Create Docker Image

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#247]
Create an official Docker image and make it available at some open Docker registry, such as https://hub.docker.com/. A couple of Dockerfiles currently exist that can be used to create the image.

* https://github.com/sscpac/statick/blob/master/templates/Dockerfile
* https://github.com/kkredit/statick-docker

Provide documentation on how to use the official Docker image for local projects and within automated continuous integration services.

**Comment by tdenewiler** [comment]
Initial work has started.

https://hub.docker.com/repository/docker/tdenewiler/statick

Eventually pushing new Docker images could be done as part of the CI process with Github Actions.

https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by tdenewiler** [comment]
As of #392 Docker images are created on each new release and available from GitHub Packages.

https://github.com/sscpac/statick/pkgs/container/statick

```shell
docker pull ghcr.io/sscpac/statick:latest
```

Thanks @gregtkogut!

**Comment by gregtkogut** [comment]
Minor comment on the docker images.   They are currently "pinned" to the statick release, but if the images are re-created using the Github workflow run manually, they will allow most library and OS dependencies to update to the latest release, not the version released at the time of the statick release..  This introduces minor risk, and I thought about version-pinning every dependency (a recommended Docker practice for release images).    But decided against it for now.
