### ISSUE TITLE
Create Github Action

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#248]
Github recently released a tool called [Super Linter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/). They have made it easy to use it with [Github Actions](https://github.com/github/super-linter#example-connecting-github-action-workflow). We should do something similar with Statick in order to make it easier for folks to use the tool.

**Comment by tdenewiler** [comment]
Nice additional features would be to have the Statick output:
* displayed as a comment in a pull request (similar to how Codecov does it)
* generate per line comments in the pull request diff (or per file comments if line information is unavailable)

**Comment by tdenewiler** [comment]
A decent looking example that might help get this started is:

https://blog.jessfraz.com/post/the-life-of-a-github-action
https://github.com/jessfraz/branch-cleanup-action

**Comment by tdenewiler** [comment]
This looks like a simple example that we could emulate. Would just need to figure out how to pass in desired arguments to Statick, such as `--user-paths` and `--profile`.

https://github.com/jidicula/clang-format-action

**Comment by tdenewiler** [comment]
Lots of work happening at sscpac/statick-action:#1.

**Comment by denewiler** [comment]
@gregtkogut did this work over at https://github.com/sscpac/statick-action. Thanks!
