### ISSUE TITLE
Allow multiple clang-format configuration filenames

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#258]
Right now Statick requires `~/_clang-format` to be the name and location of the configuration file for the clang-format tool. But the clang-format tool also allows the configuration file to be `~/.clang-format`, which shows up as a hidden file in Linux and is not normally displayed when listing files. For that reason we want to support using either file as the configuration file for the clang-format tool.

In order to preserve backwards compatibility with existing users I want to add this feature in where Statick first looks for `~/_clang-format`. Only if that file is not found will Statick look for `~/.clang-format`. If neither file is found it will be the same as the current behavior when `_clang-format` does not exist.

**Comment by denewiler** [comment]
Fixed by #264
