### ISSUE TITLE
Allow message regex exceptions to only apply to a files from a file glob

### ISSUE THREAD

**Issue by xydesa** [sscpac/statick#259]
It would be nice if we could limit the files that a message regex exception applies to. For instance, we may want to ignore chktex warnings for `Wrong length of dash may have been used.` but only inside .bib files where a single dash can be used in ISBN and DOI numbers.

  doi = {10.1007/s10514-012-9321-0},
  isbn = {978-3-642-13408-1}

https://github.com/sscpac/statick/blob/master/statick_tool/exceptions.py#L149

Adding something like this inside exceptions.yaml:
      - tools: [chktex]
        globs: [".*.bib"]
        regex: "Wrong length of dash may have been used."

**Comment by denewiler** [comment]
Fixed by #266
