### ISSUE TITLE
pylint requirement <2.0 for Python 2.7

### ISSUE THREAD

**Issue by zlacelle** [sscpac/statick#260]
16.04 / Kinetic still requires Python 2.7, and pylint > 2.0 requires Python 3+. 

In requirements.txt, change
pylint
to
pylint<2.0

**Comment by zlacelle** [comment]
After continuing with the process, it seems that statick install instructions might only be for python3. This makes sense, but it might make sense to make that clear early on in the instructions. For instance, on Ubuntu 16.04 with ROS Kinetic installed, the commands "pip install" and "python setup.py" need to be replaced with "pip3 install" and "python3 setup.py"

**Comment by tdenewiler** [comment]
Yeah, sorry about the confusion. I'll update the documentation soon to make it more clear that Statick is Python3 only.

**Comment by denewiler** [comment]
The README was updated to make installation methods more clear. Hopefully it is easier for future users to get started with Statick. Thanks for bringing this up.
