### ISSUE TITLE
clang binaries not working with default install.txt

### ISSUE THREAD

**Issue by zlacelle** [sscpac/statick#265]
When installing statick using pip3 install statick, then using install.txt to install required packages in Ubuntu (happens to be 16.04), the resulting clang binaries (3.9) don't automatically create the non-versioned version of the soft links in /usr/bin.

For example, there is no "clang-tidy", but "clang-tidy-3.9". These are all soft links to the /usr/llvm/* directory either way.

Then, when using the default plugins for clang, clang-tidy, and clang-format, the binaries aren't found. My workaround was to create extra softlinks from /usr/local/bin/clang-tidy to /usr/bin/clang-tidy-3.9, but not sure if you want to handle this differently!

Great tool pipeline, by the way.

**Comment by tdenewiler** [comment]
That is an oversight in the `install.txt` file. I will update that file to include some defaults that will work for some folks. The key is to install the generic clang tools via apt on Ubuntu. I do this when running unit tests in Github Actions.

https://github.com/sscpac/statick/blob/master/.github/workflows/test.yml

I would strongly recommend that you remove the manually created symlinks in system directories. If you have manually created files in `/usr/` it can interfere with automated tools such as apt.

For your specific issue you should run the following commands after using `install.txt`:

```shell
sudo apt install clang clang-tidy clang-format
```

Note that a single set of packages for `install.txt` will be difficult to maintain such that it works for all users. I have started seeing that the difference in versions between Ubuntu 16.04 and Ubuntu 20.04 is great enough that you have to start customizing at least a few of the packages that get installed. The recently updated README file no longer references `install.txt` for this reason.

Please let me know if you continue to have issues. I appreciate the feedback.

**Comment by zlacelle** [comment]
Yup, makes sense. You could take the ROS-y approach and maintain a xenial-devel, bionic-devel, focal-devel, etc, where install.txt is correct per version. I can also manage this manually, but in case you add support for new tools, I'd rather trust your install list.

**Comment by tdenewiler** [comment]
I think syncing extra branches would be difficult to maintain. But something like `install.txt`, `install-xenial.txt`, `install-focal.txt` might work. I'll start thinking more about how we can make dependency installation easier for non-PyPI packages.
