### ISSUE TITLE
PEP8 and PEP257 tools have been renamed

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#28]
Apparently they're officially 'pycodestyle' and 'pydocstyle' (and apparently have been for a couple years now -- I never noticed until I saw a warning message today!). PyPI and the executables themselves currently allow the old names as aliases, but it would be good to rename the Statick modules and change the pip dependencies for the sake of consistency with upstream and for future-proofing.

References: https://github.com/PyCQA/pycodestyle/issues/466 https://github.com/PyCQA/pydocstyle/issues/172

**Comment by tdenewiler** [comment]
That's a good idea. I'll start working on that. I'll try to support configuration files that use either name for the tool, such as a `config.yaml` that has either `pycodestyle` *or* `pep8` flags both being used by the `pycodestyle` tool.

**Comment by denewiler** [comment]
Addressed with #29.
