### ISSUE TITLE
ROS 2 Python only packages are not discovered by ros_discovery_plugin

### ISSUE THREAD

**Issue by xydesa** [sscpac/statick#286]
https://index.ros.org/doc/ros2/Tutorials/Creating-Your-First-ROS2-Package/

ROS 2 python only packages do not have/need CMakeLists.txt files. This means they don't satisfy the requirements in the ros_discovery_plugin to be a ros package.

**Comment by tdenewiler** [comment]
The initial fix I will try is to look for the following in the ROS discovery plugin:

1. Same as now, and keep this check first. If there is a `package.xml` file and `CMakeLists.txt` file then we can say it is a ROS package. We will use `ROS_VERSION` to determine if it is ROS1 or ROS2.
2. Add this if only `package.xml` is in a Statick package. If `package.xml` has the following tag then it is a ROS2 package:

    <build_type>ament_python</build_type>

**Comment by denewiler** [comment]
Fixed in #288.

**Comment by denewiler** [comment]
Need to re-open. The changes to address this broke `statick_ws` for some users. See #291. We will have to come up with a way to do this while fixing the bugs.

**Comment by denewiler** [comment]
Previous bugs were fixed and this is now available in v0.4.10. See #297 for updated method of discovery. See #291 where bugs were verified fixed.
