### ISSUE TITLE
ros_discovery_plugin error when running statick_ws on a ROS 1 workspace with statick 0.4.8

### ISSUE THREAD

**Issue by mlanting** [sscpac/statick#291]
I just updated to 0.4.8, and when I try running against a workspace, it gets to the 12th package, and crashes with the following error:
```

---Discovery---
Running C discovery plugin...
  0 C/C++ files found.
C discovery plugin done.
Running perl discovery plugin...
  0 Perl files found.
perl discovery plugin done.
Running ros discovery plugin...
Traceback (most recent call last):
  File "/usr/local/bin/statick_ws", line 168, in <module>
    main()
  File "/usr/local/bin/statick_ws", line 97, in main
    issues, dummy = statick.run(package[1], parsed_args)
  File "/usr/local/lib/python3.5/dist-packages/statick_tool/statick.py", line 283, in run
    plugin.scan(package, level, self.exceptions)
  File "/usr/local/lib/python3.5/dist-packages/statick_tool/plugins/discovery/ros_discovery_plugin.py", line 57, in scan
    and "build_type" in output["package"]["export"]
TypeError: argument of type 'NoneType' is not iterable
```

Also, it seems to be finding twice as many packages as it should. Version 0.4.8 is finding 390 packages, 0.4.7 finds 195 and does not have issues running on the same workspace.

**Comment by denewiler** [comment]
Sorry @mlanting. I will revert the changes to the ROS discovery plugin and make a new release. That should be done within 2 hours.

Later I will do more testing on my side to see if I can bring the changes back without the bugs. So far I have not been able to re-create the bug you found with ROS1 or ROS2 workspaces. Ideally, I want to re-create the bug prior to making a release that supports ROS2 packages without `CMakeLists.txt`. The last thing I want to do is cause crashes again.

I also have not seen `statick_ws` find double the number of packages.

I have a few questions if you have time and the ability to answer:

1. Is your workspace ROS1 or ROS2?
2. Does the package that crashed have a `CMakeLists.txt` file?
3. Can you post a stripped-down version of the `package.xml` file in the package (without any proprietary information)?
4. Do you have any subdirectories with a `package.xml` file that are not ROS packages?

Thanks.

**Comment by denewiler** [comment]
@mlanting, there is a new release available on PyPI, v0.4.9. Please let me know if you see any problems with that version. Thanks.

**Comment by mlanting** [comment]
1. It does
2. When I was looking at the package.xml file to see what would be left after stripping it down, i noticed one of the dependencies is listed twice under both <build_depend> and <run_depend>. It's pretty bare-bones apart from that.
3. I don't think so, I'll take a closer look

**Comment by mlanting** [comment]
I did some more digging and got it to fail on a different package, though this second one doesn't have a double entry in the dependencies list. This time it gets through a little over 100 packages before the failure instead of just 12, and I'm noticing that it's not finding any issues, whereas it finds quite a few when I run the version that works (I have yet to test 0.4.9, i'll do that soon). It also runs really fast through the packages before crashing as though the packages it scans are empty. When it somehow doubles the amount of packages it sees, it seems the extra ones are just empty "shells".

I'll see about getting you some sanitized files.

**Comment by tdenewiler** [comment]
v0.4.10 was just released and should properly support discovery of ROS2 Python-only packages without crashing (#297). @mlanting, #304 should also have fixed the issue you saw with a doubling of the number of discovered ROS packages when running `statick_ws`. That fix is included in v0.4.10. if you have any further issues please let me know.

**Comment by mlanting** [comment]
I ran a test with v0.4.10 and everything seems to be working as expected. Thanks!

**Comment by denewiler** [comment]
Thanks for the update @mlanting.
