### ISSUE TITLE
Use CATKIN_IGNORE for subdirectories

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#295]
Statick is not using CATKIN_IGNORE as intended. Based on this Q&A from ROS Answers:

https://answers.ros.org/question/208180/how-to-use-catkin_ignore-file-correctly/

CATKIN_IGNORE should ignore the package that file is in *and all subdirectories*. Statick does not ignore the subdirectories. We should fix that. It is only used by `statick_ws`.

This showed up when running Statick against the top-level of a workspace instead of the src directory of that workspace. Extra ROS packages were discovered in the workspace/.catkin_tools subdirectory, even though there was a CATKIN_IGNORE file in the .catkin_tools directory. Note that this was first discovered when trying to add support for ROS2 Python-only packages that do have a `package.xml` file and do not have a `CMakeLists.txt` file. The subdirectories in .catkin_tools matched this new pattern.

**Comment by denewiler** [comment]
Fixed by #304.
