### ISSUE TITLE
Add instructions for statick_ws

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#296]
The new version of the README does not include instructions for how to run `statick_ws`. That should be added in. Make sure to point out that `statick_ws` should point to the `src/` directory of a workspace (or a subdirectory of the `src/` directory). For example, given the following directory layout for the workspace:

* /home/user/ws
  * src
    * package1
    * package2
    * subdir
      * package3
      * package4
      * package5
  * build
  * devel

Statick should be invoked as

```shell
statick_ws /home/user/ws/src --output-directory <output directory>
```

or

```shell
statick_ws /home/user/ws/src/subdir --output-directory <output directory>
```

**Comment by denewiler** [comment]
Added in #303.
