### ISSUE TITLE
Lizard does not accept flags from config

### ISSUE THREAD

**Issue by jhdcs** [sscpac/statick#298]
It appears that the `lizard` plugin doesn't use any user-specified flags from the `config.yaml` file. Checking the code at [lizard_tool_plugin.py](https://github.com/sscpac/statick/blob/master/statick_tool/plugins/tool/lizard_tool_plugin.py), the subprocess call in `scan` shows that user flags aren't apparently implemented...

**Comment by denewiler** [comment]
Thanks for the report, I'll look into this.
