### ISSUE TITLE
Investigate using lizard as Python module

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#299]
A tool plugin for lizard already exists. That plugin uses `subprocess` to run the actual tool and get the output. However, there is a Python module available for lizard. We should investigate using the Python module instead of `subprocess`.

https://github.com/terryyin/lizard#using-lizard-as-python-module

**Comment by jhdcs** [comment]
I can take a poke at this, if you'd like. I was already looking at adding in flags.

**Comment by denewiler** [comment]
@jhdcs, that would be great! I'll be around most of today to help if you have any questions. Thanks.
