### ISSUE TITLE
Idea: support dependency analyzers

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#30]
What do you think of adding dependency analyzers (e.g. https://www.owasp.org/index.php/OWASP_Dependency_Check) to Statick? A project I'm working on is using the OWASP scanner regularly and I think it's a pretty useful security tool, but I'm not sure whether adding support for it would go outside of the intended "static analysis" scope of this project.

**Comment by tdenewiler** [comment]
I would be in favor of adding a plugin to support Dependency Check in Statick. This looks like a tool that can help us write better software. And it would then be up to a user to configure their Statick runs to enable this tool or not, depending on whether they find the output valuable.

Dependency check might technically go outside the "static analysis" scope, but we do not need that to be a constraint for where development of Statick goes.

**Comment by tdenewiler** [comment]
Some documentation that might help writing the tool plugin:

Install: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html
Command line arguments: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html

**Comment by tdenewiler** [comment]
I'm open to working on these plugins in the future, but I do not have plans to write them in the near-term. Closing for now, but this issue can be re-opened if someone wants to work on it.
