### ISSUE TITLE
Inheriting from config.yaml

### ISSUE THREAD

**Issue by zlacelle** [sscpac/statick#327]
I have a "standard" statick config set up complete with config.yaml, and a user path with things like exceptions.yaml. I'd also like to create a custom config that inherits from a level from config.yaml. I.e.:

config.yaml
  levels:
    default_level:
      <etc>
custom-config.yaml
  levels:
    custom_level:
      inherits_from: default_level
      <etc>

I don't think this is possible right now: If I specify my own custom config using --config, it doesn't first read the default config.

**Comment by tdenewiler** [comment]
I am pretty sure you are correct about the current behavior. I'll test it out to verify. If your use case is not currently possible I'll try to add in support. That seems like a useful feature.

**Comment by zlacelle** [comment]
Great, that would be appreciated! This will minimize the duplicate configs for our organization and let us do things like, say, disable certain catkin_lint warnings on certain projects. The main goal is to be able to change command-line flags for each tool at the project level while not having to maintain large config.yamls within every project.

**Comment by tdenewiler** [comment]
For an update: I have something working in a forked branch. I just need to get a few more lines covered by unit tests before I open a PR.

https://github.com/tdenewiler/statick/tree/chain-config-levels

**Comment by tdenewiler** [comment]
@zlacelle, #337 is open implementing these changes. We'll give you a couple days to try it out and/or review the changes if you want to.

**Comment by zlacelle** [comment]
@tdenewiler Very nice, I'll give it a try sometime next week. Thanks for the quick PR!

**Comment by denewiler** [comment]
Feature added in #337. Feel free to re-open if the problem persists. Expect a new release this weekend that has this feature.
