### ISSUE TITLE
Fix setup.py install

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#347]
From #344, there seem to be issues running `sudo python3 setup.py install`. The error is

```shell
error: can't copy 'statick_tool/rsc/plugin_mapping': doesn't exist or not a regular file
```

This is probably because `plugin_mapping` is a directory and not a file. We should fix `setup.py` so that the `install` command works.

**Comment by tdenewiler** [comment]
I was unable to re-create this issue. However, I did not have a machine available for testing as a regular user. The way I tested was to use Docker, which I have installed on an Ubuntu 20.04 host and configured such that my regular user can run.

On host:
1. docker pull ubuntu
2. docker run -it ubuntu bash

On Docker (as root):

1. apt update
2. apt install git python3 python3-pip
3. git clone https://github.com/tdenewiler/statick
4. cd statick
5. pip3 install -r requirements.txt
6. python3 setup.py install
7. statick --help

I see the Statick help output. I see the binary at `/usr/local/bin/statick`. I see the package files at `/usr/local/lib/python3.8/dist-packages/statick_tool/`.

**Comment by tdenewiler** [comment]
If anyone wants to take a crack at this in the future, please feel free.

**Comment by mlanting** [comment]
I am able to recreate the issue if I use the ubuntu:xenial docker and follow your steps. Xenial uses python 3.5 instead of 3.8 so maybe it's something to do with that.

**Comment by tdenewiler** [comment]
I tried this again today, based on another report of local installs not working. I ran into errors as well. I'll try to provide a fix for local installs.

**Comment by tdenewiler** [comment]
The steps that are working for some of us are similar to the original steps with a small change to the command to install Statick. Instead of installing from local sources, we can install using pip and a git repository. You can specify a non-default branch as well.

On host:

1. docker pull ubuntu
2. docker run -it ubuntu bash

On Docker (as root):

1. apt update
2. apt install -y git python3 python3-pip
3. python3 -m pip install git+https://github.com/sscpac/statick.git
4. statick --help

The final command should show all of the available arguments to Statick. Additionally, you should find `which statick` shows that Statick is installed to `/usr/local/bin/statick`.

To use a custom branch you could do something like `python3 -m pip install git+https://github.com/user/statick.git@custom-branch`. The `custom-branch` could be a branch name or a commit hash.

https://pip.pypa.io/en/stable/reference/pip_install/#git
https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by denewiler** [comment]
Alternate installation instructions have been added to README.
