### ISSUE TITLE
Add Scheduled and Manual Workflow Initiation

### ISSUE THREAD

**Issue by gregtkogut** [sscpac/statick#382]
Scheduled build/tests (as opposed to the current method of triggering workflows on pull request or push) would more quickly reveal issues cause by reasons other than a change to the repository, e.g. underlying libraries.

Manually initiated builds might be convenient in some cases, e.g. verifying that a failure is repeatable and not the result of a spurious hiccup in a remote server, etc.

**Comment by denewiler** [comment]
Now available as part of #383.
