### ISSUE TITLE
Maven projects

### ISSUE THREAD

**Issue by xydesa** [sscpac/statick#388]
Maven projects seem to revolve around [pom.xml files](https://maven.apache.org/pom.html). Does it make sense to discover directories containing those files as packages for statick?

**Comment by tdenewiler** [comment]
We already have the [maven](https://github.com/sscpac/statick/blob/main/statick_tool/plugins/discovery/maven_discovery_plugin.py) and [Java](https://github.com/sscpac/statick/blob/main/statick_tool/plugins/discovery/java_discovery_plugin.py) discovery plugins.

**Comment by xydesa** [comment]
True, but they're not considered packages by statick. Statick only looks for ["package.xml"](https://github.com/sscpac/statick/blob/main/statick_tool/statick.py#L474) and it seems to me that "pom.xml" files might serve the same purpose for maven projects.
