### ISSUE TITLE
Make a consistent scheme for discovery plugin output

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#42]
Right now, all of the discovery plugins save what they find to the package dictionary, but the scheme is pretty inconsistent - some plugins differentiate src and bin files, some are setting true/false, the cmake flag is only true or unset, etc. I think statick would benefit internally by coming up with a more consistent scheme. Off the top of my head, it would be useful to have a practical way to differentiate between "nothing found" and "plugin wasn't run." I'm imagining something like namespacing each discovery plugin within the package[], so for example we would have package['cmake']['src_dir']. The further problem (which I don't really have an answer for yet) is that some plugins overlap, e.g. the cmake plugin and C plugin are both finding C files.

**Comment by creffett** [comment]
Also, any consistent naming scheme will run into issues just because each language has its own set of file types - C has source and headers, XML and YAML don't have "source" files per se, etc.

**Comment by tdenewiler** [comment]
I didn't come up with a good answer for how to do this. Most of the discovery plugins have unit test coverage now.
