### ISSUE TITLE
Default configs do not use suggested new list format for "inherits_from"

### ISSUE THREAD

**Issue by gregtkogut** [sscpac/statick#425]
Should the default configs be updated to use the new list format for _inherits_from_?

**Comment by xydesa** [comment]
Yea, i think that change should be made.

**Comment by gregtkogut** [comment]
I haven't been seeing that warning as far as I can remember, but haven't been looking...I'll update every deprecated instance of the keyword in all the repos, and on the side test to see if that deprecation warning is being displayed.
