### ISSUE TITLE
CMake should discover .cmake files

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#431]
Some CMake files have a `.cmake` extension. The discovery plugin should look for that extension.

**Comment by tdenewiler** [comment]
https://cmake.org/cmake/help/latest/manual/cmake-language.7.html

**Comment by tdenewiler** [comment]
Added in #434.

**Comment by xydesa** [comment]
We forgot to update the README to add `*.cmake` to the list of extensions found by the CMake discovery plugin.

**Comment by xydesa** [comment]
> We forgot to update the README to add `*.cmake` to the list of extensions found by the CMake discovery plugin.

I added this change to #435
