### ISSUE TITLE
CMake discovery plugin fails with catkin, generates wrong CATKIN_DEVEL_PREFIX

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#44]
I've got a Catkin package which fails when cmake_discovery_plugin actually runs CMake. Relevant snippets:

`-- PROJECT: [NAME:dsat_lsa][SRC_DIR:/home/jenkins/workspace/ROSM_rtk-statick_master-XIVWAOJYVSYPP4AQ5FZIKKA755OLWXMYAKWA4FWMINIDWHGUV7YA/rtk/src/DCS/dsat_lsa][BIN_DIR:/home/jenkins/workspace/ROSM_rtk-statick_master-XIVWAOJYVSYPP4AQ5FZIKKA755OLWXMYAKWA4FWMINIDWHGUV7YA/statick_output/dsat_lsa-sei_cert]
...
-- Using CATKIN_DEVEL_PREFIX: /home/jenkins/workspace/ROSM_rtk-statick_master-XIVWAOJYVSYPP4AQ5FZIKKA755OLWXMYAKWA4FWMINIDWHGUV7YA/statick_output/dsat_lsa-sei_cert/devel
...
-- catkin 0.7.14
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:297 (message):
  catkin_package() absolute include dir
  '/home/jenkins/workspace/ROSM_rtk-statick_master-XIVWAOJYVSYPP4AQ5FZIKKA755OLWXMYAKWA4FWMINIDWHGUV7YA/statick_output/dsat_lsa-sei_cert/deps/live555-05032012_64build/UsageEnvironment/include/'
  does not exist
`

The basic problem: because Statick's CMake discovery plugin runs from the temporary output directory rather than the source directory, CMAKE_SOURCE_DIR doesn't point to the source code. This doesn't seem to cause problems most of the time, but in this case I think Catkin is actually verifying that some of the headers exist and then fails when they don't.

**Comment by tdenewiler** [comment]
I have not been able to re-create this issue. I'm going to close for now, but feel free to re-open and provide an example in the future.
