### ISSUE TITLE
Add timing results to output

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#442]
It could be insightful to add timing results of each step that we print if the `print_to_console` reporting plugin is enabled. I'm imagining output like the following.

| Plugin | Plugin Type | Duration (s) |
| :------- | :--------------- | :--------------- |
| Walk Path | Discovery     | 5                |
| A        | Discovery     | 1                |
| B        | Discovery     | 3                |
| C        | Discovery     | 2                |
| D        | Discovery     | 3                |
| E        | Tool              | 24               |
| F        | Tool              | 13               |
| G        | Reporting     | 1                |
| H        | Reporting     | 3                |
| Total   |                     |  55              |

**Comment by denewiler** [comment]
Closed by #443.
