### ISSUE TITLE
Replace findbugs with spotbugs (with backwards compatibility?)

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#46]
Findbugs is no longer maintained as of 2016, spotbugs is the community-supported fork/successor. Spotbugs doesn't seem to be packaged by Ubuntu, so I'm thinking something like the following:

* Rename the findbugs plugin -> spotbugs
* Have some logic in that plugin which uses spotbugs if present, else findbugs
  * If findbugs is present and spotbugs is not, maybe print a warning?

While we're at it, http://find-sec-bugs.github.io/ (a spotbugs extension) might also be neat to add, but that might be entirely up to the user to configure.

**Comment by tdenewiler** [comment]
I'll look into this. I like the idea of using supported tools.

**Comment by creffett** [comment]
Handled in #102
