### ISSUE TITLE
Automatically upload new tags to PyPI

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#55]
See https://docs.travis-ci.com/user/deployment/pypi/ for documentation on how to do that without exposing the password.

**Comment by tdenewiler** [comment]
There is a bug in Travis that makes it so deploying to PyPI does not work. Our log is at https://travis-ci.org/sscpac/statick/builds/485093257. The error is:

    Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/pip'

This matches an error reported at https://github.com/travis-ci/travis-ci/issues/9701. Following that you get to https://github.com/gnocchixyz/gnocchi/issues/949, which has a big list of other users reporting the same thing.

I'll try to keep an eye on those issues to see when they get fixed. For now I'll just manually do releases.

**Comment by tdenewiler** [comment]
I figured out a way to do this using Github Actions in tdenewiler/statick-tex#26. I'm going to try to solve this issue with that approach for this package as well. It will be part of a bigger switch from Travis to Actions.

**Comment by denewiler** [comment]
Done in #219.
