### ISSUE TITLE
Question: How to write statick plugin packages?

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#70]
More a question than an issue. I'm looking at adding a plugin to Statick to support MicroFocus Fortify, and wanted to try writing it as a separate module (so it would be, say, `pip install statick-fortify-plugin` which would depend on statick). Any experience with making this sort of arrangement work with Yapsy? The documentation is a bit lacking, but it looks like the usual approach with Yapsy is to define a plugins dir and drop everything in there (which is doable, but kind of defeats the purpose of `pip install`ing things)

**Comment by tdenewiler** [comment]
That is a good use case to support. The closest thing we have done is to make a custom plugin in a separate directory that is made available via the `--user-paths` flag. There is an example at:

https://github.com/tdenewiler/statick/tree/master/examples/navigation/navigation_config/plugins

It is run in example 3 (and 4 and 5):

https://github.com/tdenewiler/statick/blob/master/examples/navigation/navigation_example3.bash

We are still getting used to releasing code, so I'm not sure if we could make that an independent module that is on PyPI. When trying to use the new plugin the `--user-paths` argument doesn't seem to make sense for installed modules.

If I'm missing the point of what you are asking let me know as I'd be happy to help figure it out. I'm willing to try making an example and adding documentation.

**Comment by creffett** [comment]
You're correct about what I'm asking. It would be a big refactor, but I'm wondering if something like the setuptools [entry_point mechanism](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) might be a better approach to supporting this use case? I believe flake8 uses that approach.

**Comment by tdenewiler** [comment]
I came across this yapsy feature request and it sounds like exactly what you want to do:

https://sourceforge.net/p/yapsy/feature-requests/11/

I tried to find the example the author was talking about and the closest I got was in their documentation:

http://yapsy.sourceforge.net/#modify-plugin-descriptions-and-detections

There is a method to set the location to look for plugins but the documentation is not very clear to me:

http://yapsy.sourceforge.net/PluginFileLocator.html#yapsy.PluginFileLocator.PluginFileLocator.setPluginPlaces

I'll try to spend some time making a minimal Statick example to see if it is feasible with yapsy.

**Comment by creffett** [comment]
I'm currently working on adding Fortify support as a plugin, see https://github.com/soartech/statick-fortify. Right now, it works because it tells Python to install everything into statick_tool. It works, but I'm not sure how robust it is - that is, whether it's possible for Python to try to install this into a separate directory.

**Comment by tdenewiler** [comment]
I don't know how robust yapsy plus `setup.py` configuration will be either. I think it's worth starting with this approach though. I like what you have started with the Fortify plugin.

I have a working TeX discovery plugin and plan to add tool plugins for lacheck (#40) and chktex (#41). I can make those plugins live in a separate repository and use them to document how to create external plugins for Statick.

**Comment by denewiler** [comment]
I updated the Users Guide to point to your fortify plugin and my tex plugin as examples of how to write Statick plugins that are located in a separate repository and released on PyPI as individual packages.
