### ISSUE TITLE
Improve Maven root-POM identification

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#73]
Right now, the Maven plugin identifies root POMs through a naive "shortest directory path" approach. This could fail if root POMs are at different levels (e.g. a/b/pom.xml and b/c/d/pom.xml) and technically the root POM does not have to be at the highest directory. This could be improved by parsing all POMs, finding each one's name, parent, and children, and building a tree (or series of trees) of dependency relationships to identify the root POMs. This is future work/technical debt - I expect that for most repos, there will only be one root POM and the naive approach will work fine.

**Comment by tdenewiler** [comment]
I do not have Maven experience or examples that highlight the issue. I'm going to close this for now, but feel free to re-open in the future if you want the improvement.
