### ISSUE TITLE
Switch to using pytest-pydocstyle vice pytest-py257 in tox.ini

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#79]
Unfortunately not a simple switch - pytest-pydocstyle is Python 3 only. We probably need a list for post-2.7-deprecation issues, this belongs on it.

**Comment by tdenewiler** [comment]
This can be done if #170 is approved. That issue addresses dropping support for Python 2.7.

**Comment by denewiler** [comment]
Fixed in #214.
