### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#86]
Add support for codecov tool to display code coverage of unit tests. I think it will be as simple as following https://github.com/codecov/example-python#testing-with-tox. That should just be to add the following to `tox.ini`:

```
[testenv]
passenv = CI TRAVIS TRAVIS_*
deps = codecov
commands = codecov
```

There may be an issue of having this repository being owned by an organization rather than an individual.

**Comment by denewiler** [comment]
Fixed by #93.
